before:
  hooks:
    - go mod tidy

builds:
  - id: docker-mcp
    main: ./cmd/docker-mcp
    binary: docker-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w  # Reduce binary size
      - -X github.com/coolbit-in/docker-mcp/pkg/version.Version={{.Version}}
      - -X github.com/coolbit-in/docker-mcp/pkg/version.GitCommit={{.ShortCommit}}
      - -X github.com/coolbit-in/docker-mcp/pkg/version.BuildDate={{.Date}}
    # Special handling for Windows
    ignore:
      - goos: windows
        goarch: arm64  # Windows ARM64 support is not mature yet

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/examples/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  # Automatically generate changelog from git commits
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  mode: replace
  # Add download buttons and instructions to GitHub Release page
  header: |
    ## Docker MCP (Model Context Protocol) {{.Version}}
    
    This is a binary release of Docker MCP version {{.Version}}

    ### Installation Guide
    
    1. Download the version for your operating system
    2. Extract the archive and move the binary to a location in your PATH
    3. Ensure the file has execute permissions (on Linux/macOS use `chmod +x docker-mcp`) 