name: Release Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发工作流

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以便生成正确的版本信息
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # 更新为Go 1.23
          cache: true  # 启用Go依赖缓存以加速构建
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 